server:
  port: 8090
spring:
  application:
    name: kettle
  freemarker:
    cache: false
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  datasource:
      url: jdbc:mysql://171.113.161.31:33016/kettle?useUnicode=true&characterEncoding=UTF8&useSSL=false
      username: root
      password: 123456
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
env:
  databases:
    - dbfrom
    - dbto
    - taxi-user
    - taxi-account
    - taxi-trade
    - taxi-coupon
    - taxi-bi
    - taxi-system
    - taxi-credits
    - taxi-finance
    - taxi-notification
    - taxi-gateway
  from-dbs:
    - PROD
    - TEST
    - LOCAL
  to-dbs:
    - LOCAL
    - TEST
  db-settings:
    - name: LOCAL
      host: 171.113.161.31
      port: 33016
      user: root
      password: 123456
    - name: TEST
      host: 171.113.161.31
      port: 33016
      user: root
      password: 123456
    - name: PROD
      host: 171.113.161.31
      port: 33016
      user: root
      password: 123456